name: labar10
description: Labar10 — Resume Builder (MVVM)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Routing
  go_router: ^17.0.0

  # State management
  provider: ^6.0.5

  # SQLite для Desktop, Windows, MacOS, Linux, Android
  sqflite_common_ffi: ^2.3.6

  # SQLite для Web
  sqflite_common_ffi_web: ^1.0.1+2

  # Flutter SQLite wrapper
  sqflite: ^2.4.0

  # Для роботи з шляхами файлів
  path: ^1.8.3

  # SharedPreferences для зберігання теми
  shared_preferences: ^2.1.1

  google_mobile_ads: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true


